apiVersion: apps/v1
kind: Deployment
metadata:
  name: produits-deplo
  labels:
    app: produits-deplo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: produits-deplo
  template:
    metadata:
      labels:
        app: produits-deplo
    spec:
      containers:
        - name: produits-deplo
          image: younessaabaoui/produits-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: produits-service
spec:
  ports:
    - targetPort: 9001
      port: 80
  selector:
    app: produits-deplo