apiVersion: apps/v1
kind: Deployment
metadata:
  name: paiements-deplo
  labels:
    app: paiements-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paiements-deplo
  template:
    metadata:
      labels:
        app: paiements-deplo
    spec:
      containers:
        - name: paiements-deplo
          image: younessaabaoui/paiement-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9003

---
apiVersion: v1
kind: Service
metadata:
  name: paiements-service
spec:
  ports:
    - targetPort: 9003
      port: 80
  selector:
    app: paiements-deplo