apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deplo
  labels:
    app: config-server-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-deplo
  template:
    metadata:
      labels:
        app: config-server-deplo
    spec:
      containers:
        - name: config-server-deplo
          image: younessaabaoui/config-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9101
            
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  ports:
    - targetPort: 9101
      port: 80
  selector:
    app: config-server-deplo