apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deplo
  labels:
    app: client-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-deplo
  template:
    metadata:
      labels:
        app: client-deplo
    spec:
      containers:
        - name: client-deplo
          image: younessaabaoui/client-server:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  ports:
    - targetPort: 8080
      port: 80
  selector:
    app: client-deplo