apiVersion: apps/v1
kind: Deployment
metadata:
  name: springadmin-deplo
  labels:
    app: springadmin-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springadmin-deplo
  template:
    metadata:
      labels:
        app: springadmin-deplo
    spec:
      containers:
        - name: springadmin-deplo
          image: younessaabaoui/microservice-springadmin:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9105

---
apiVersion: v1
kind: Service
metadata:
  name: springadmin-service
spec:
  ports:
    - targetPort: 9105
      port: 80
  selector:
    app: springadmin-deplo