apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deplo
  labels:
    app: gateway-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-deplo
  template:
    metadata:
      labels:
        app: gateway-deplo
    spec:
      containers:
        - name: gateway-deplo
          image: younessaabaoui/gateway-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9004

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9004
      protocol: TCP
  selector:
    app: gateway-deplo